### ISSUE TITLE
Serious issue in MapCache.swift

### ISSUE THREAD

**Issue by strongwillow** [merlos/MapCache#17]
In the `loadTile` function, you are downloading tiles even if they are found in cache. `result` will be called twice.

You should put the downloading task in the `fetChfailure` block.

**Comment by strongwillow** [comment]
But still, it's a good project. I have some improvements in mind and may contribute

**Comment by kkieffer** [comment]
Looking at your pull request I can see your point.  But my question is, what is the paradigm for the cache? Notwithstanding the issue of calling "result" twice, it seems like the current paradigm is to return the cached tile first, then try and reload from the server and update again with the latest tile.  This has the advantage of always getting the most recent data (when internet is available) but using additional bandwidth.

Perhaps there could be an option that specifies what the user would like:

1.  If found in cache, always return the cached value, and never update from server

2.  If fetch from server succeeds, always return the latest, and update the cache

3.  If found in cache, return the cached value, but update it from server ONLY if the date of the tile is older than some period.

**Comment by strongwillow** [comment]
I see that's a design choice to always get the latest. Especially for OSM which updates everyday, if missing one update the map may look shattered.

My app uses commercial tile services instead of free OSM tiles (which looks bad on retina display). For each tile, I need to pay for it. That's why I try to limit network access. The good part is my tile server updates roughly every month. That gives me a good window of one month cache.

For me, map cache needs to takes care of two things:
1. Map data should be fresh and of same version (tiles should be perfectly connected)
2. Network traffic usage should be low

They are countering each other. The fresher the data, the more traffic. Actually your three points are exactly the two extremes and one balance. So I agree with you.

Just brainstorming here. I'm thinking about keeping the most frequently used tiles fresh. We see those map tiles more often so it better be fresh. The algorithm is simple. Keep a cache hit counter for each tile. If the counter is divisible by a number, say 5, then discards this tile and load again. In this way, a tile will be reloaded at 1st, 6th, 11th... access.

One bonus is that the hit counter can be used to select which to discard when cache is full, with the Least-frequently used (LFU) algorithm.

**Comment by kkieffer** [comment]
Even if you're using a free service, there's good reason to use cache.  When on cellular data, you'll use up data constantly reloading tiles.  And it takes longer than pulling from disk. One option is to use the [Reachability library](https://github.com/ashleymills/Reachability.swift) to see what type of connection you're on.  If Wi-fi, refresh tiles from server always.  If cellular, maybe only old tiles or not at all.

Ultimately it will be up to @merlos to decide, maybe he could make loadTile take an option on how to fetch.

**Comment by strongwillow** [comment]
That's also a possibility. Let's see what he has to say

**Comment by merlos** [comment]
Thanks @strongwillow for the PR, I looked at it and it fixes some bugs I was struggling with. Let me do some tests and I´ll merge it. 

@kkieffer Good points that you raised.

The initial paradigm I thought was to load from network/server only if the tile was not in the cache or it had expired. In that sense, the fix of @strongwillow in #18 is correct.

However, I see value on the download strategies you mentioned in the thread. These are  strategies that you mentioned as well as some other I diverged from:

* UPDATE_EXPIRED: Returns tiles from the cache whenever they are in disk and have not expired. Loads from server in other case.

* CACHE_TILE_THEN_UPDATE_EXPIRED: Returns the cached version (for performance), but if network is available and tile has expired, download the tile from server. The difference with the one above is that it always returns first the cached version independently of the expiration status.

* CACHE_TILE_THEN_UPDATE_ALWAYS: Returns the cached version, but if network is available then download the tile from server independently of the expiration status.

* CACHE_TILE_THEN_UPDATE_ALWAYS_WIFI: Same as CACHE_TILE_THEN_UPDATE_ALWAYS, but updates only in Wifi. If user is in another network, only update when the tile expired.

I have two questions:
1. For CACHE_TILE_THEN_*, my question is if the `loadTile` returns the cached version and then returns again a fresh tile, will the map display the latter or it will only display the fresh version next time the map needs to display this same tile.

2. Do you think that CACHE_TILE_THEN_UPDATE_ALWAYS_* strategies make much sense for a cache?

The next point is by @strongwillow. He poses to add a counter to each tile and download most used tiles. Some thoughts.

1. Although I see what is the rational behind it - which is related to his particular use case - we should consider if the scenario can be a generalized one. I am saying this because, in general, the goal of a caches is to avoid the download multiple times the most used resources, and there is already a parameter that defines when a resource is no longer valid which is the expiration time... so it sounds a bit counter intuitive for me this as a general strategy...
2. Related with the retention policy. Every time a tile is retrieved from the cache, modification date is updated to current time, therefore tiles that are more commonly used would already have less probabilities of being demoted.

Thank you both for the discussion!

**Comment by kkieffer** [comment]
@merlos regarding your first question, I do not know the answer.  However I like the options you presented.  Would you provide config settings that let the user change the strategy as well as the expiration time?

UPDATE_EXPIRED: Good use case when the user wants to minimize network access while retaining mostly current data.  But should always return the cached version if network is down?  Better to return an expired tile than nothing at all.

CACHE_TILE_THEN_UPDATE_EXPIRED: Not sure about this option. The user gets the older data, still incurs the bandwidth of the fetch, and won't get the new tile until the next app load (assuming the MKMapKit caches tiles in RAM). If the map will take two closures (one for the cache, the next for when the update occurs), this option could be viable

CACHE_TILE_THEN_UPDATE_ALWAYS: Don't think this one makes sense. Uses bandwidth always and has the disadvantage of the one above.

CACHE_TILE_THEN_UPDATE_ALWAYS_WIFI: Like this one. Wifi is kind of "unlimited" usually.  Might as well get the most recent tiles.
